<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SauceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sauces')->insert([
            [
                'userId' => 1,
                'name' => 'Spicy Mango',
                'manufacturer' => 'Tropical Heat',
                'description' => 'A sweet and spicy mango sauce.',
                'mainPepper' => 'Habanero',
                'imageUrl' => 'https://www.sauce-piquante.fr/77-large_default/marie-sharps-sauce-mango-habanero.jpg',
                'heat' => 7,
                'likes' => 10,
                'dislikes' => 2,
                'usersLiked' => json_encode([1, 2, 3]),
                'usersDisliked' => json_encode([4]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 2,
                'name' => 'Garlic Inferno',
                'manufacturer' => 'Hot & Spicy Co.',
                'description' => 'A fiery garlic sauce for spice lovers.',
                'mainPepper' => 'Ghost Pepper',
                'imageUrl' => 'https://hellfirehotsauce.com/cdn/shop/products/InfieronoRed-new_1024x1024.jpg?v=1681856765',
                'heat' => 9,
                'likes' => 25,
                'dislikes' => 5,
                'usersLiked' => json_encode([2, 3, 5]),
                'usersDisliked' => json_encode([1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 3,
                'name' => 'Smoky Chipotle',
                'manufacturer' => 'BBQ Masters',
                'description' => 'A rich and smoky chipotle sauce.',
                'mainPepper' => 'Chipotle',
                'imageUrl' => 'https://sweetpepper.fr/cdn/shop/files/image_378cf439-93f2-42d7-8a3b-f1766bbe88b3_png.webp?v=1706460549',
                'heat' => 5,
                'likes' => 15,
                'dislikes' => 3,
                'usersLiked' => json_encode([3, 4, 6]),
                'usersDisliked' => json_encode([2]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 4,
                'name' => 'Sweet Chili',
                'manufacturer' => 'Asian Delights',
                'description' => 'A perfect balance of sweet and spicy.',
                'mainPepper' => 'Thai Chili',
                'imageUrl' => 'https://m.media-amazon.com/images/I/61rKvMgVkCL.jpg',
                'heat' => 4,
                'likes' => 20,
                'dislikes' => 1,
                'usersLiked' => json_encode([1, 5, 6]),
                'usersDisliked' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 5,
                'name' => 'Caribbean Heat',
                'manufacturer' => 'Island Flavors',
                'description' => 'A tropical sauce with a fiery kick.',
                'mainPepper' => 'Scotch Bonnet',
                'imageUrl' => 'https://www.mitiendita.fr/477-home_default/sauce-chile-habanero-caribbean.jpg',
                'heat' => 8,
                'likes' => 30,
                'dislikes' => 4,
                'usersLiked' => json_encode([2, 4, 5]),
                'usersDisliked' => json_encode([3]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 6,
                'name' => 'Lemon Zest',
                'manufacturer' => 'Citrus Creations',
                'description' => 'A tangy lemon-infused hot sauce.',
                'mainPepper' => 'Cayenne',
                'imageUrl' => 'https://www.aldersons.co.nz/cdn/shop/products/aldersons-zest-hot-sauce_1400x.jpg?v=1653960418',
                'heat' => 6,
                'likes' => 18,
                'dislikes' => 2,
                'usersLiked' => json_encode([1, 3, 6]),
                'usersDisliked' => json_encode([5]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 7,
                'name' => 'Wasabi Blast',
                'manufacturer' => 'Fusion Flavors',
                'description' => 'A bold and spicy wasabi sauce.',
                'mainPepper' => 'Wasabi',
                'imageUrl' => 'https://m.media-amazon.com/images/I/71t8nmvTAlL.jpg',
                'heat' => 7,
                'likes' => 22,
                'dislikes' => 6,
                'usersLiked' => json_encode([2, 4, 7]),
                'usersDisliked' => json_encode([1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => 8,
                'name' => 'Extreme Heat',
                'manufacturer' => 'Burning Sensation',
                'description' => 'For those who dare to try the hottest.',
                'mainPepper' => 'Carolina Reaper',
                'imageUrl' => 'https://saucecrafters.com/cdn/shop/products/sbextrmain1.png?v=1626868052&width=533',
                'heat' => 10,
                'likes' => 40,
                'dislikes' => 10,
                'usersLiked' => json_encode([3, 5, 8]),
                'usersDisliked' => json_encode([2, 6]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
